### ISSUE TITLE
raise EOFError

### ISSUE THREAD

**Issue by BlackDeal** [thu-ml/tianshou#219]
###  exception-raising bug raise EOFError
```
**Process Process-1:
Traceback (most recent call last):
  File "/home/admin615/anaconda3/envs/gym_torch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/admin615/anaconda3/envs/gym_torch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/admin615/gym_work/tianshou/tianshou/env/worker/subproc.py", line 36, in _worker
    obs, reward, done, info = env.step(data)
  File "/home/admin615/gym_work/tianshou/examples/FOC_ENV.py", line 192, in step
    self.obs_s,done =  self.get_observation()
  File "/home/admin615/gym_work/tianshou/examples/FOC_ENV.py", line 153, in get_observation
    self.time_obs =float(self.data_all_s[0])
ValueError: could not convert string to float: 
Epoch #1:   0%|          | 17735/24000000 [3:06:25<4201:26:57,  1.59it/s, len=19127.00, loss/actor=107.649990, loss/critic1=19.110306, loss/critic2=19.309036, n/ep=1.00, n/st=19127.00, rew=-10251.95, v/ep=0.00, v/st=18.82]
Traceback (most recent call last):
  File "/home/admin615/anaconda3/envs/gym_torch/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/admin615/Downloads/pycharm-community-2020.2.1/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/admin615/Downloads/pycharm-community-2020.2.1/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/admin615/gym_work/tianshou/examples/ts_sac2.py", line 171, in <module>
    test_sac_bipedal()
  File "/home/admin615/gym_work/tianshou/examples/ts_sac2.py", line 157, in test_sac_bipedal
    args.batch_size, stop_fn=IsStop, save_fn=save_fn, writer=writer)
  File "/home/admin615/gym_work/tianshou/tianshou/trainer/offpolicy.py", line 86, in offpolicy_trainer
    result = train_collector.collect(n_step=collect_per_step)
  File "/home/admin615/gym_work/tianshou/tianshou/data/collector.py", line 281, in collect
    self.data.act, id=self._ready_env_ids)
  File "/home/admin615/gym_work/tianshou/tianshou/env/venvs.py", line 212, in step
    obs, rew, done, info = conn.get_result()
  File "/home/admin615/gym_work/tianshou/tianshou/env/worker/subproc.py", line 181, in get_result
    obs, rew, done, info = self.parent_remote.recv()
  File "/home/admin615/anaconda3/envs/gym_torch/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/admin615/anaconda3/envs/gym_torch/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/admin615/anaconda3/envs/gym_torch/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process Process-2:
Traceback (most recent call last):
  File "/home/admin615/anaconda3/envs/gym_torch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/admin615/anaconda3/envs/gym_torch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/admin615/gym_work/tianshou/tianshou/env/worker/subproc.py", line 36, in _worker
    obs, reward, done, info = env.step(data)
  File "/home/admin615/gym_work/tianshou/examples/FOC_ENV.py", line 234, in step
    self.reset()
  File "/home/admin615/gym_work/tianshou/examples/FOC_ENV.py", line 398, in reset
    reset_o = self.get_observation()
  File "/home/admin615/gym_work/tianshou/examples/FOC_ENV.py", line 149, in get_observation
    self.data_all = self.tcpSerSock.recv(self.TCPServerData["DataSize"]).decode('utf-8')
ConnectionResetError: [Errno 104] Connection reset by peer**
```

```python
>>> print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
0.2.6 1.4.0 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] linux
```

What's the problem? Thank you！！！

**Comment by Trinkle23897** [comment]
Here:
```
File "/home/admin615/gym_work/tianshou/examples/FOC_ENV.py", line 192, in step
    self.obs_s,done =  self.get_observation()
  File "/home/admin615/gym_work/tianshou/examples/FOC_ENV.py", line 153, in get_observation
    self.time_obs =float(self.data_all_s[0])
ValueError: could not convert string to float
```
Your `self.data_all_s[0]` in your FOC_ENV.py seems not working, so please print this value to find out the error.

**Comment by Trinkle23897** [comment]
I think it is better to optimize the FOC_ENV first since the training speed is too slow for your case. Usually, at least ~60 FPS is acceptable (1.5 FPS in your case)

**Comment by BlackDeal** [comment]
Thanks,i'll try.
