### ISSUE TITLE
atari_dqn.py example error 5-dimensional input of size [32, 4, 4, 84, 84]

### ISSUE THREAD

**Issue by mg64ve** [thu-ml/tianshou#287]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [X] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

Hello, nice framework.
I have just cloned the current version and tried to run atari_dqn.py with only --logdir=/tmp/log parameter.
I am getting the following error:

```
Observations shape: (4, 84, 84)
Actions shape: 6
/opt/conda/lib/python3.8/site-packages/tianshou/data/buffer.py:348: UserWarning: ListReplayBuffer will be replaced in version 0.4.0.
  warnings.warn("ListReplayBuffer will be replaced in version 0.4.0.")
Epoch #1:   0% 0/10000 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/srv/examples/atari/atari_dqn.py", line 163, in <module>
    test_dqn(get_args())
  File "/srv/examples/atari/atari_dqn.py", line 152, in test_dqn
    result = offpolicy_trainer(
  File "/opt/conda/lib/python3.8/site-packages/tianshou/trainer/offpolicy.py", line 125, in offpolicy_trainer
    losses = policy.update(batch_size, train_collector.buffer)
  File "/opt/conda/lib/python3.8/site-packages/tianshou/policy/base.py", line 170, in update
    batch = self.process_fn(batch, buffer, indice)
  File "/opt/conda/lib/python3.8/site-packages/tianshou/policy/modelfree/dqn.py", line 100, in process_fn
    batch = self.compute_nstep_return(
  File "/opt/conda/lib/python3.8/site-packages/tianshou/policy/base.py", line 261, in compute_nstep_return
    target_q_torch = target_q_fn(buffer, terminal)  # (bsz, ?)
  File "/opt/conda/lib/python3.8/site-packages/tianshou/policy/modelfree/dqn.py", line 83, in _target_q
    a = self(batch, input="obs_next").act
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tianshou/policy/modelfree/dqn.py", line 149, in forward
    logits, h = model(obs_, state=state, info=batch.info)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/srv/examples/atari/atari_network.py", line 48, in forward
    return self.net(x), state
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 4, 8, 8], but got 5-dimensional input of size [32, 4, 4, 84, 84] instead
```

I am running in docker and these are my versions:

```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tianshou, torch, sys
>>> print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
0.3.1 1.7.1 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] linux
```

any idea why this error?

**Comment by Trinkle23897** [comment]
How did you install tianshou? `pip install .` or `pip install tianshou`

**Comment by Trinkle23897** [comment]
Could you please use `pip3 install tianshou` or checkout tag `v0.3.1` and install the source code via `pip3 install -e .`? I know the issue but we have fixed it in #280. However it will not be merged soon. Sorry about that.

**Comment by Trinkle23897** [comment]
Also there's another temporary solution: change the definition of ReplayBuffer to 
```python
    # replay buffer: `save_last_obs` and `stack_num` can be removed together
    # when you have enough RAM
    buffer = ReplayBuffer(args.buffer_size, ignore_obs_next=True)
```

**Comment by mg64ve** [comment]
Hi @Trinkle23897 ,

in my Dockerfile I was using:

`RUN pip install git+https://github.com/thu-ml/tianshou.git@master --upgrade`

and I replaced with:

`RUN pip install tianshou`

it now works.
Please check your master branch.
Thanks.

**Comment by Trinkle23897** [comment]
Now it works: `pip install git+https://github.com/thu-ml/tianshou.git@master --upgrade`
