### ISSUE TITLE
test rendering with docker

### ISSUE THREAD

**Issue by mg64ve** [thu-ml/tianshou#288]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [X] documentation request (i.e. "X is missing from the documentation.")
    + [X] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [X] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

Hello, did anyone try to execute a test/example in docker and get rendering?
I have tried many options and nothing seems to work.
Most of the times I am getting:
```

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

{'best_result': '200.00 ± 0.00',
 'best_reward': 200.0,
 'duration': '5.27s',
 'test_episode': 100.0,
 'test_speed': '33634.95 step/s',
 'test_step': 20000,
 'test_time': '0.59s',
 'train_episode': 141.0,
 'train_speed': '2539.89 step/s',
 'train_step': 11885,
 'train_time/collector': '2.66s',
 'train_time/model': '2.02s'}
Traceback (most recent call last):
  File "/srv/test/discrete/test_pg.py", line 98, in <module>
    test_pg()
  File "/srv/test/discrete/test_pg.py", line 93, in test_pg
    result = collector.collect(n_episode=1, render=args.render)
  File "/opt/conda/lib/python3.8/site-packages/tianshou/data/collector.py", line 292, in collect
    self.env.render()
  File "/opt/conda/lib/python3.8/site-packages/tianshou/env/venvs.py", line 262, in render
    return [w.render(**kwargs) for w in self.workers]
  File "/opt/conda/lib/python3.8/site-packages/tianshou/env/venvs.py", line 262, in <listcomp>
    return [w.render(**kwargs) for w in self.workers]
  File "/opt/conda/lib/python3.8/site-packages/tianshou/env/worker/dummy.py", line 38, in render
    self.env.render(**kwargs) if hasattr(self.env, "render") else None
  File "/opt/conda/lib/python3.8/site-packages/gym/core.py", line 240, in render
    return self.env.render(mode, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/gym/envs/classic_control/cartpole.py", line 174, in render
    from gym.envs.classic_control import rendering
  File "/opt/conda/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/opt/conda/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/window/__init__.py", line 591, in __init__
    context = config.create_context(gl.current_context)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

```
the last command I have tried is the following:

`docker run --privileged=true --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/marco/local_projects/tianshou:/srv --gpus all mg/tianshou:v1.7.1a python3 /srv/test/discrete/test_pg.py --seed 0 --render 0.03 --logdir=/tmp/log
`

the following is the environment in the docker container:

![image](https://user-images.githubusercontent.com/22278227/107272314-d09e6680-6a4d-11eb-8618-05de0368e9c3.png)

**Comment by Trinkle23897** [comment]
Could you please check out if only contains the following script work in your docker?
```python
import gym
env = gym.make("CartPole-v0")
env.reset()
env.render()
```

It doesn't seem like a tianshou-related issue.

**Comment by mg64ve** [comment]
Hi @Trinkle23897 , you are right it is not a Tianshou issue:
```

[marco@wks tianshou]$ docker run --privileged=true -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/marco/local_projects/tianshou:/srv --gpus all mg/tianshou:v1.7.1a python3 /srv/examples/test_issue.py 
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/srv/examples/test_issue.py", line 4, in <module>
    env.render()
  File "/opt/conda/lib/python3.8/site-packages/gym/core.py", line 240, in render
    return self.env.render(mode, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/gym/envs/classic_control/cartpole.py", line 174, in render
    from gym.envs.classic_control import rendering
  File "/opt/conda/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/opt/conda/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/window/__init__.py", line 591, in __init__
    context = config.create_context(gl.current_context)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/opt/conda/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

```
any reccomendation to get rid of this issue?

**Comment by Trinkle23897** [comment]
Maybe your Dockerfile lacks some configurations about opengl, see https://github.com/openai/gym/issues/468

**Comment by mg64ve** [comment]
You are right @Trinkle23897 there was a dockerfile problem.
But now I fixed it and I can connect with VNC to the docker container.
If I run the following example:

```
import gym
import sys
import time

env = gym.make("CartPole-v0")
env.reset()
env.render()
time.sleep(200)

```
I am getting the following:

![image](https://user-images.githubusercontent.com/22278227/107660315-6a515800-6c88-11eb-9ea5-2894ab1afbda.png)

But if I run:

`#python3 atari_dqn.py --epoch 1 --render=0.03`

I am not getting any rendering:

![image](https://user-images.githubusercontent.com/22278227/107660790-ed72ae00-6c88-11eb-9b32-43934a8f0aac.png)

My docker file is:
```

FROM pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update 
RUN apt-get install -y --no-install-recommends build-essential \
         cmake \
         git \
         curl \
         python3-opengl \
         ca-certificates \
         supervisor xinetd x11vnc xvfb tinywm openbox xdotool wmctrl x11-utils xterm \
         libgl1-mesa-glx \
         libjpeg-dev \
         libnvidia-gl-450-server \
         libpng-dev && \
     rm -rf /var/lib/apt/lists/*


RUN conda install -y ipykernel jupyter

RUN pip install git+https://github.com/thu-ml/tianshou.git@master --upgrade
RUN pip install pandas matplotlib opencv-python gym atari-py

# Create conda user, get anaconda by web or locally
RUN useradd --create-home --home-dir /home/condauser --shell /bin/bash condauser

# Setup our environment for running the ipython notebook
# Setting user here makes sure ipython notebook is run as user, not root
USER condauser
ENV HOME=/home/condauser
ENV SHELL=/bin/bash
ENV USER=condauser
WORKDIR /home/condauser/notebooks

RUN mkdir ~/.vnc && touch ~/.vnc/passwd
RUN x11vnc -storepasswd "vncdocker" ~/.vnc/passwd
EXPOSE 5900

CMD ["/usr/bin/x11vnc", "-forever", "-usepw", "-create"]

```

What do you think?

**Comment by mg64ve** [comment]
One second, it seems rendering is after training:

![image](https://user-images.githubusercontent.com/22278227/107690745-cf1daa00-6caa-11eb-8623-0e110dccb67a.png)

I thought it was also possible during training. Is it possible?

**Comment by Trinkle23897** [comment]
I don't think there's anyone who wants to call `.render()` in training because it slows down the training process.
But if you really want to render in training process, you can either add the `render` argument in `collector.collect`, or modify the collector's code here: https://github.com/thu-ml/tianshou/blob/f528131da1de604f8158a1fe132e1fada71950e0/tianshou/data/collector.py#L291-L293

**Comment by mg64ve** [comment]
Of course you are right @Trinkle23897 .
But maybe for troubleshooting or debugging it could be a good option.
Thanks for your clarifications, I have tested it and it works.
Please close this issue.
Cheers.

**Comment by mg64ve** [comment]
Sorry @Trinkle23897 , one more question.
Is it possible to call watch() after the end of each epoch training?

**Comment by Trinkle23897** [comment]
I don't think it is possible with gym API. However you can save to video format and render it offline.
