### ISSUE TITLE
BrokenPipeError and EOFError when reset in SubprocVectorEnv

### ISSUE THREAD

**Issue by amoyplane** [thu-ml/tianshou#436]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.2 1.9.0 1.20.3 3.8.11 (default, Aug  3 2021, 15:09:35) 
  [GCC 7.5.0] linux
  ```

Hello, thanks for this project.

I meet with some problems, here is the console log:

```
Traceback (most recent call last):
  File "./src/testrl3.py", line 118, in <module>
    train_collector.collect(n_step=start_timesteps, random=True)
  File "/home/admin/miniconda3/envs/work/lib/python3.8/site-packages/tianshou/data/collector.py", line 261, in collect
    obs_reset = self.env.reset(env_ind_global)
  File "/home/admin/miniconda3/envs/work/lib/python3.8/site-packages/tianshou/env/venvs.py", line 166, in reset
    obs_list = [self.workers[i].reset() for i in id]
  File "/home/admin/miniconda3/envs/work/lib/python3.8/site-packages/tianshou/env/venvs.py", line 166, in <listcomp>
    obs_list = [self.workers[i].reset() for i in id]
  File "/home/admin/miniconda3/envs/work/lib/python3.8/site-packages/tianshou/env/worker/subproc.py", line 163, in reset
    obs = self.parent_remote.recv()
  File "/home/admin/miniconda3/envs/work/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/admin/miniconda3/envs/work/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/admin/miniconda3/envs/work/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError


Traceback (most recent call last):
  File "./src/testrl3.py", line 118, in <module>
    train_collector.collect(n_step=start_timesteps, random=True)
  File "/home/admin/miniconda3/envs/work/lib/python3.8/site-packages/tianshou/data/collector.py", line 261, in collect
    obs_reset = self.env.reset(env_ind_global)
  File "/home/admin/miniconda3/envs/work/lib/python3.8/site-packages/tianshou/env/venvs.py", line 166, in reset
    obs_list = [self.workers[i].reset() for i in id]
  File "/home/admin/miniconda3/envs/work/lib/python3.8/site-packages/tianshou/env/venvs.py", line 166, in <listcomp>
    obs_list = [self.workers[i].reset() for i in id]
  File "/home/admin/miniconda3/envs/work/lib/python3.8/site-packages/tianshou/env/worker/subproc.py", line 162, in reset
    self.parent_remote.send(["reset", None])
  File "/home/admin/miniconda3/envs/work/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/admin/miniconda3/envs/work/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/admin/miniconda3/envs/work/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```
Two kinds of error happens sometime, without certain pattern. I try different settings for number of train_envs and test_envs but it still occur. It seems that error happens when reset env. In my env class, I will disconnect old simulator(using PyBullet) and connect to a new one when reset. May this cause the error raise by multiprocessing? Thank you.

**Comment by amoyplane** [comment]
Thanks for @Trinkle23897's help. Hard to reproduce the problem but can be avoid by using ```pybullet.resetSimulation()``` to reset env without reconection with simulation engine

**Comment by xl3783** [comment]
if the env.reset contains new objects:
```
self.agents = [Agent()]
self.viewer = Viewer(84, 84, visible=False)
```
also cause the EOFError.

**Comment by Trinkle23897** [comment]
Now sure what's going wrong, but a temporary fix is to use DummyVectorEnv instead of Subprocess/Shmem.

@amoyplane have you encountered this issue?

**Comment by amoyplane** [comment]
@Trinkle23897 

In older version of my code I new a object in env.reset() and EOFError occurs, but in stable version env.reset() doesn't contains that opration.
I am not sure but that might be the keypoint.
