### ISSUE TITLE
cannot run example 'pong_ppo.py'

### ISSUE THREAD

**Issue by DZ9** [thu-ml/tianshou#9]
Epoch #1:   0%|                                                                              | 0/1000 [00:00<?, ?it/s]Process Process-1:
Process Process-2:
Process Process-3:
Process Process-5:
Process Process-4:
Process Process-6:
Process Process-7:
Process Process-8:
Traceback (most recent call last):
  File "/home/z/anaconda2/envs/py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/z/anaconda2/envs/py36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/z/anaconda2/envs/py36/lib/python3.6/site-packages/tianshou/env/vecenv.py", line 99, in worker
    p.send(env.step(data))
  File "/home/z/anaconda2/envs/py36/lib/python3.6/site-packages/tianshou/env/atari.py", line 75, in step
    _, reward, terminal, info = self.env.step(action)
  File "/home/z/anaconda2/envs/py36/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 113, in step
    action = self._action_set[a]
IndexError: index 94 is out of bounds for axis 0 with size 6

**Comment by Trinkle23897** [comment]
@Mehooz Your code

**Comment by DZ9** [comment]
I found the problem and commit a pr. you can check if you wanna merge it.
